export { default as Admin } from './Admin'
export { default as HomeAdmin } from './Home'
export { default as QrScanner } from './QrScan'
export { default as CreateMonHoc } from './CreateMonhoc'
export { default as Dsmonhoc } from './Danhsachmonhoc'
export { default as CreateTGMonHoc } from './CreateTimeMH'
