export { default as Header } from './Header'
export { default as InputField } from './inputField'
export { default as Button } from './button'
export { default as Footer } from './Footer'
export { default as QrCode } from './qrcode'
export { default as QRScanner } from './QRScanner'
export { default as HeaderAdmin } from './HeaderAdmin'
export { default as InputForm } from './inputs/inputsForm'
export { default as Button1 } from './Button1'
export { default as TextInput} from './TextInput'