export { default as Header } from './Header'
export { default as InputField } from './inputField'
export { default as Button } from './button'
export { default as Footer } from './Footer'
export { default as QrCode} from './qrcode'